### ISSUE TITLE
MAUI

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/Samples#11]

**Comment by leastprivilege** [comment]
We will do this once MAUI is released.

**Comment by lnaie** [comment]
Excited. Where is the link?

**Comment by leastprivilege** [comment]
It's here
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/main/Maui

**Comment by ehsangfl** [comment]
this is only authentication. we need a complete sample that get data through HttClient from server API that has "authorize" attribute.
