### ISSUE TITLE
UseDatabaseErrorPage(IApplicationBuilder) is obsolete and will be removed in a future version

### ISSUE THREAD

**Issue by alexis-** [DuendeSoftware/Samples#15]
https://github.com/DuendeSoftware/Samples/blob/b3273d8b6f2f7006ba008ecd41f6e6b07ee9725c/IdentityServer/v5/Quickstarts/5_AspNetIdentity/src/IdentityServerAspNetIdentity/Startup.cs#L74

FYI, the `UseDatabaseErrorPage(IApplicationBuilder)` method is marked as obsolete in the latest (non pre-release) version of Microsoft.AspNetCore (5.0.5.0).

```
Warning	CS0618	'DatabaseErrorPageExtensions.UseDatabaseErrorPage(IApplicationBuilder)' is obsolete: 'This is obsolete and will be removed in a future version. Use DatabaseDeveloperPageExceptionFilter instead, see documentation at https://aka.ms/DatabaseDeveloperPageExceptionFilter.'
```

**Comment by brockallen** [comment]
Thanks -- we'll update the templates once we change them to target .NET 6.

**Comment by brockallen** [comment]
https://github.com/aspnet/Announcements/issues/432
