### ISSUE TITLE
Update Samples to v7

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/Samples#151]
- [x] AspNetIdentity
- [x] Basics
   - [x] ClientCredentials
   - [x] Introspection
   - [x] MvcBasic
   - [x] MvcTokenManagement
   - [x] MvcBackChannelLogout
   - [x] JwtBasedClientAuthentication
   - [x] MvcJarJwt
   - [x] MvcPar
- [x] BFF
   - [x] Angular
   - [x] React
   - [x] Blazor WASM
   - [x] JS
   - [x] Yarp
   - [x] DPoP
   - [x] Split Hosts
   - [x] Token Exchange
- [x] Configuration
    - [x] Permissions
    - [x] PipelineRegistration
    - [x] SimpleDcr
    - [x] SoftwareStatement 
- [x] DPoP
- [x] MTLS
- [x] PAT
- [x] Scopes and Resources
- [x] Session Management
- [x] Session Migration
- [x] Token Exchange
- [x] User Interaction
   - [x] Ciba
   - [x] Dynamic Providers
   - [x] ProfileService
   - [x] SpaLoginUi
   - [x] StepUp
   - [x] WindowsAuthentication
   - [x] WsFederationDynamicProviders

**Comment by brockallen** [comment]
If you search thru the filesystem in the ~/v7 directory I still see many project references still using IS v6.x:

![image](https://github.com/DuendeSoftware/Samples/assets/649492/e5c87fb2-e258-4e62-a3b4-7fde8a6f05a4)

**Comment by josephdecock** [comment]
> If you search thru the filesystem in the ~/v7 directory I still see many project references still using IS v6.x:

Thanks for catching that! Looks like there were a couple of branches (including one with all the UserInteraction samples) that still needed to be merged.

**Comment by brockallen** [comment]
Looks like these are all done now, except for the Otel one, which is tracked here: https://github.com/DuendeSoftware/Samples/issues/170
