### ISSUE TITLE
Example on how to secure a dotnet 5 Azure Function

### ISSUE THREAD

**Issue by jcnewman83** [DuendeSoftware/Samples#19]
I would like to request for a sample to demonstrate how I can secure my dotnet 5 Azure functions which run under an isolated process using Duende Identity Server as my IDP.

**Comment by leastprivilege** [comment]
Hi - thanks!

We can add that. Generally speaking, there is nothing special to do beyond "standard" JWT validation, but Googling shows a lot of sub-optimal results.

I will work on it ASAP.

**Comment by leastprivilege** [comment]
Hey - I have added the sample here:

https://docs.duendesoftware.com/identityserver/v5/samples/misc/#securing-azure-functions-client

Let me know if you have any questions!
