### ISSUE TITLE
Logout link broken on JS example

### ISSUE THREAD

**Issue by pdevito3** [DuendeSoftware/Samples#20]
On [this line](https://github.com/DuendeSoftware/Samples/blob/9000852e24e8f76990f2860657dc22a2ce4ffa3e/IdentityServer/v5/BFF/JsBffSample/FrontendHost/wwwroot/session.js#L21) of the JS example, I believe the query should say `bff:logout_url` instead of `bff:logout`

**Comment by brockallen** [comment]
Fix, thanks.
