### ISSUE TITLE
What are the prerequisites for running the maui sample?

### ISSUE THREAD

**Issue by obrungot** [DuendeSoftware/Samples#206]
Cloning the MauiApp1 project, and running it from Visual Studio 2022 causes exceptions.
Running as a Windows App.

Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
'MauiApp1.exe' (CoreCLR: clrhost): Loaded 'D:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. 

![2024-08-12_23-29-53](https://github.com/user-attachments/assets/76ee89c5-2561-4fb5-82e2-7f93fe007309)

**Comment by RolandGuijt** [comment]
Currently the sample doesn't run as a Windows App. It does work on Android and iOS.

**Comment by josephdecock** [comment]
If you're looking for a sample windows application, we have several available in the IdentityModel.OidcClient.Samples repo: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

**Comment by obrungot** [comment]
> If you're looking for a sample windows application, we have several available in the IdentityModel.OidcClient.Samples repo: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

I was hoping it could be done in Maui, but for Windows. I will deploy to Android, but I've found debugging in Windows is a lot more efficient than debugging witht he Android emulators.

**Comment by obrungot** [comment]
> Currently the sample doesn't run as a Windows App. It does work on Android and iOS.

Thanks, that good to know. Just starting with Maui I prefer debugging in Windows and not using Android emulators. If my understanding is correct it's due to the WebAuthenticator (https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-8.0&source=recommendations&tabs=windows) 

Do you know of another approach that could work on Maui Windows?

**Comment by josephdecock** [comment]
Yes, we use the WebAuthenticator in the Maui sample and it only supports android and iOS - that's the underlying limitation. I think that the other approaches that we show in our wpf and winforms samples ought to work in maui as well, if you're building a maui windows app. But it sort of sounds like you're mostly using windows for debugging and ultimately need mobile platform support. There's no single tool that I'm aware of that handles all 3 in a simple way, unfortunately.

**Comment by obrungot** [comment]
Thanks @josephdecock and @RolandGuijt
