### ISSUE TITLE
Failed to push authorization parameters while authenticate from Maui Android App

### ISSUE THREAD

**Issue by obrungot** [DuendeSoftware/Samples#208]
I've tried to configure both my identityserver and maui android app as shown in the samples.
There is however something which is causing an issue, most likely on the IDP side.

On login from the maui application I get invalid_request
![2024-08-15_22-18-08](https://github.com/user-attachments/assets/f47fc85c-4dea-470a-8e9c-62afe7a373c2)

On the IDP, I've configured it as the "interactive.public" in the demo.duendesoftware.com sample.
//demo.duendesoftware.com
```
new Client
{
	ClientId = "interactive.public",
	ClientName = "Interactive client (Code with PKCE)",

	RedirectUris = { "https://notused" },
	PostLogoutRedirectUris = { "https://notused" },

	RequireClientSecret = false,

	AllowedGrantTypes = GrantTypes.Code,
	AllowedScopes = AllScopes,

	AllowOfflineAccess = true,
	RefreshTokenUsage = TokenUsage.OneTimeOnly,
	RefreshTokenExpiration = TokenExpiration.Sliding
},
```

//On my IdentityServer
```
new Client
{
	ClientId = "test.android",
	ClientName = "Interactive client (Code with PKCE)",

	RedirectUris = { "https://notused" },
	PostLogoutRedirectUris = { "https://notused" },

	RequireClientSecret = false,

	AllowedGrantTypes = GrantTypes.Code,
	AllowedScopes =
	{
		IdentityServerConstants.StandardScopes.OpenId,
		IdentityServerConstants.StandardScopes.Profile,
		"roles",
		"api"
	},

	AllowOfflineAccess = true,
	RefreshTokenUsage = TokenUsage.OneTimeOnly,
	RefreshTokenExpiration = TokenExpiration.Sliding
}
```
If I try to login in my maui app, it works if I use demo.duendesoftware.com as authority, but not when I run on my setup.

//Maui
```
            builder.Services.AddSingleton(new OidcClient(new()
            {
                Authority = "https://localhost:5001",
                ClientId = "test.android",
                //Authority = "https://demo.duendesoftware.com",
                //ClientId = "interactive.public"

                Scope = "openid",
                RedirectUri = "myapp://callback",

                Browser = new MauiAuthenticationBrowser()
            }));
```
What am I missing?

**Comment by josephdecock** [comment]
If you have a basic identity server license, pushed authorization is not included and you'll get this error when the OIDC client library attempts to push. This is a known issue where identity server will include par in the discovery document even though par is disabled by the license. We intend to fix identity server to not do that in an upcoming release.

For now, you can disable PAR in the OIDC client options to work around this.

**Comment by obrungot** [comment]
Regarding the license, I have a Community Edition, which to my understanding is feature equivalent to the Enterprise Edition.

I've disabled PAR which works against the demo.duendesoftware.com, but I get invalid_request from my instance. 

![2024-08-16_07-41-13](https://github.com/user-attachments/assets/0e2e7d8c-ce92-4472-bd45-0350e03d8689)

Currently logging is disabled, so I don't have any more details, but I'll look into it later today. 

Thanks again.

**Comment by josephdecock** [comment]
Ok, then yes you shouldn't be having a licensing issue. I would read the identity server logs to find out which authorize parameters aren't right.

**Comment by obrungot** [comment]
It seems to be an issue with the callback path

From the IDP log
2024-08-18 10:35:16.323 -07:00 [DBG] Start authorize request protocol validation
2024-08-18 10:35:16.325 -07:00 [DBG] client configuration validation for client test.android succeeded.
2024-08-18 10:35:16.340 -07:00 [ERR] Invalid redirect_uri: myapp://callback

I've copied the WebAuthenticationCallbackActivity.cs from the sample project

![2024-08-18_19-44-03](https://github.com/user-attachments/assets/4f49d99e-c615-4c23-b21c-9238c00c470f)
```
namespace YourNameSpace
{
    [Activity(NoHistory = true, LaunchMode = LaunchMode.SingleTop, Exported = true)]
    [IntentFilter(new[] { Android.Content.Intent.ActionView },
                  Categories = new[] { Android.Content.Intent.CategoryDefault, Android.Content.Intent.CategoryBrowsable },
                  DataScheme = CALLBACK_SCHEME)]
    public class WebAuthenticationCallbackActivity : Microsoft.Maui.Authentication.WebAuthenticatorCallbackActivity
    {
        const string CALLBACK_SCHEME = "myapp";

    }
}
```
Is it something else which must be set up in the maui app for the redirect_uri?

**Comment by josephdecock** [comment]
The demo identity server has its return url validation disabled, so that anyone can use it (for testing and demos in any environment). A real identity server is going to force the return url parameter to be an exact match of one of the pre-registered return URLs in your config.

**Comment by obrungot** [comment]
Thanks, @josephdecock. 

So if I change the client config on duende, it should work (replacing "notused" with "myapp://callback").

```
new Client
{
	ClientId = "test.android",
	ClientName = "Interactive client (Code with PKCE)",

	RedirectUris = { "myapp://callback" },
	PostLogoutRedirectUris = { "myapp://callback" },
	//RedirectUris = { "https://notused" },
	//PostLogoutRedirectUris = { "https://notused" },

	RequireClientSecret = false,

	AllowedGrantTypes = GrantTypes.Code,
	AllowedScopes =
	{
		IdentityServerConstants.StandardScopes.OpenId,
		IdentityServerConstants.StandardScopes.Profile,
		"roles",
		"api"
	},

	AllowOfflineAccess = true,
	RefreshTokenUsage = TokenUsage.OneTimeOnly,
	RefreshTokenExpiration = TokenExpiration.Sliding
}
```

**Comment by josephdecock** [comment]
Yep, that's right.

**Comment by obrungot** [comment]
That worked like a charm 👍

Thank you again for your help. I really appreciate it.
