### ISSUE TITLE
Use example.com subdomains instead of "real" domain names

### ISSUE THREAD

**Issue by wenz** [DuendeSoftware/Samples#209]
The samples are referring to "real" domain names such as alice.com, bob.com, and email.com. I would propose to change that to, say, alice.example.com, bob.example.com, and email.example.com to make crystal-clear that these really are examples. Just imagine one of those domains (especially the first two) gets cybersquatted.

**Comment by wenz** [comment]
If that change is desired, I'd create PRs for other repositories with those domain names, as well. If not, no worries. :)

**Comment by leastprivilege** [comment]
Thanks!

**Comment by wenz** [comment]
Hm, maybe we should actually use `example.com` instead of `email.example.com` (which doesn't make sense). I'll update the PR accordingly.
