### ISSUE TITLE
DPOP Validation does not seems to check the DPOP Token is signed with the private key matching the access token public key

### ISSUE THREAD

**Issue by jonathanantoine** [DuendeSoftware/Samples#214]
DPOP Validation does not seems to check the DPOP Token is signed with the private key matching the access token public key.

The DPOP validation does not seems to check that the CNF of the access token matches the CNF of the key used to sign the dpop token.

If true, you would be able to sign a DPOP token with your own private key (not the one from the client) and it will be accepted by the API

**Comment by josephdecock** [comment]
Thanks for raising this issue! It should be fixed in the linked PR.

**Comment by jonathanantoine** [comment]
Thanks for fixing it this quickly, it looks good !
