### ISSUE TITLE
Azure function JWT example bug in example

### ISSUE THREAD

**Issue by jcnewman83** [DuendeSoftware/Samples#23]
I have noticed a small bug in the Azure Function JWT validation example. (https://github.com/DuendeSoftware/Samples/blob/237fd280dfd86af1c74b2eade9c95a0ee14e22e7/various/JwtSecuredAzureFunction/JwtSecuredFunction/Token.cs#L75)

There are conditions where you could never exit the while loop, for example, when the token exception is not of type "SecurityTokenSignatureKeyNotFoundException"

I have made a change to move the tries increment outside of the if block and this has fixed it for me but thought I would flag it just in case my fix is not correct.

**Comment by leastprivilege** [comment]
I updated it. thanks!
