### ISSUE TITLE
Blazor WebAssembly Quickstart

### ISSUE THREAD

**Issue by ghost** [DuendeSoftware/Samples#3]
Hello,

Would it be possible to include a reference implementation/best practice quickstart sample demonstrating how to integrate a stand-alone Blazor WebAssembly client with IdentityServer.

I have attempted to do so following the below links with IdentityServer4 but have experienced some issues.

- https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio

- https://code-maze.com/how-to-secure-blazor-webassembly-with-identityserver4/

- https://code-maze.com/using-access-token-with-blazor-webassembly-httpclient/

- https://code-maze.com/blazor-webassembly-role-based-security-with-identityserver4/
- https://code-maze.com/atribute-based-access-control-blazor-webassembly-identityserver4/

**Comment by leastprivilege** [comment]
Thanks!

Yes we will have a look at what we think would be best practice here.

**Comment by Posinaut** [comment]
Thanks Dominick. Appreciate the reply.

**Comment by leastprivilege** [comment]
It's here
https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5/BlazorBFF

make sure to read the README

**Comment by posinautinc** [comment]
Hi Dominick, thank you for the quick turnaround on this. I'm the ghost who submitted this ask - had some organizational changes and deleted my account.

May I ask as a follow up to the example provided, would the process/configuration change for a non ASP.NET-hosted Blazor Webassembly app. Thinking of standalone Blazor webassembly as a single page app served by nginx in a Docker container here.

Also for your demo server at https://demo.duendesoftware.com is the configuration available on github to take a look? I'm having trouble finding it.

**Comment by leastprivilege** [comment]
The BFF architecture requires a host to handle the security and token storage server-side. This is our recommended approach,

**Comment by posinautinc** [comment]
Ok, thanks Dominick. I am no expert on security and will read up on this and change implementation accordingly. Many thanks for your help and guiding.

**Comment by posinautinc** [comment]
Hi Dominick, I'm having trouble understanding how to move forward in terms of configuring the ASP.Net host. Let's say I would like to allow anonymous and authenticated users in my Blazor app. Would this be possible?

From what I have been reading, in order to integrate login/logout functionality I need to implement something like the back channel as in https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5/Basics/MvcBackChannelLogout.

However, in my case the user would start off in the Blazor app as an anonymous user and the login/logout actions would be initiated from the Blazor app. Do I wire the Blazor login/logout actions to invoke actions in the host's controller? If so, how does the authentication state of the host reflect back to the Blazor client.

Apologies for being such a noob here.

**Comment by leastprivilege** [comment]
No problem. I will add more to it ASAP.

**Comment by leastprivilege** [comment]
I will update this ASAP to our new BFF framework

**Comment by leastprivilege** [comment]
@posinautinc Have you seen

https://github.com/DuendeSoftware/BFF/tree/main/samples

This is a better version. Will turn that into a standalone samples soon.

**Comment by posinautinc** [comment]
Thanks @leastprivilege - appreciate the update. I'm pre-occupied with work and another side project at the moment and will revisit when I'm free.

**Comment by lucaswalter** [comment]
Hi @leastprivilege, had a quick question. We are wanting to use the BFF package for our auth setup and I was wondering if it is is possible to move forward with a deployment setup like this:
1. Identify Server
2. BFF to proxy requests to the backend and protected APIs
3. Static Blazor WASM client deployed to something like Netlify or Cloudflare Pages?

Your message above mentions _"The BFF architecture requires a host to handle the security and token storage server-side. This is our recommended approach"_ which is still being done here in my example, but I am wondering if it is still possible to move forward with the deployment listed above.

---
If so, is there any example using this approach or documentation on this? Everything I have found uses an ASP.Net Core project to serve the blazor site.

Thansi

**Comment by leastprivilege** [comment]
This is possible - you would need to configure CORS in a way that the BFF host allows calls from the front-end.

This is not necessary when both back and frontend are the same physical application.

**Comment by leastprivilege** [comment]
@lucaswalter  Sorry - I didn't find time to create a sample for that specific scenario. Did you get it to work?
