### ISSUE TITLE
Samples - IdentityServerAspNetIdentity HttpContext.GetSchemeSupportsSignOutAsync depreciated

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [DuendeSoftware/Samples#33]
I'm getting the "depreciated" warning on my IdentityServer project AccountController.cs page for the HttpContext.GetchemeSupportsignOutAsync() method (see screen shot).  

This was a copy of the samples / QuickStarts provided: https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Quickstarts/5_AspNetIdentity/src/IdentityServerAspNetIdentity/Quickstart/Account/AccountController.cs - line 323

I'll try and fix it on my copy and add a comment if it appears successful.... for validation that it's correct.
<img width="1455" alt="Screen Shot 2021-12-28 at 11 21 35 am" src="https://user-images.githubusercontent.com/69283328/147511180-7cdd7e14-9af7-49b2-a8dd-1989dfe47b66.png">

**Comment by brockallen** [comment]
This is due to UI changes. Here's the [replacement](https://github.com/DuendeSoftware/IdentityServer.Templates/blob/main/src/IdentityServerInMem/Pages/Extensions.cs#L21).

**Comment by rasaconsulting-sandy** [comment]
Thanks Brock.  I had created an IdentityServer project using the V5 version template and then upgraded to the V6 libraries using NuGet.  Now I'm thinking that I should have just used the V6 template to begin with but am now a little confused as to which template to use to have the most current code (this update plus razor pages if available).

I wanted to have EF and AspNetIdentity in the same project, which I have done in my current V5-upgraded-to-V6 version.  Is the 'in memory' template the most current and the one you recommend as a starting point?

Thanks in advance for any advice you can give me.  

<img width="1255" alt="Screen Shot 2021-12-29 at 6 46 47 am" src="https://user-images.githubusercontent.com/69283328/147593214-63b4ffed-5bac-418c-bcb3-63f6314a64b0.png">

**Comment by rasaconsulting-sandy** [comment]
It looks like the 2 versions of IdentityServer that are being maintained most are the IdentityServerEmpty and IdentityServerInMem.

**Comment by brockallen** [comment]
We release sometime the week of Jan 10, 2022.

**Comment by brockallen** [comment]
I think this can be close, since we updated the QS UI for all the v6 samples.
