### ISSUE TITLE
Create Samples for ASP.NET 4.x Integration

### ISSUE THREAD

**Issue by justinsbutler** [DuendeSoftware/Samples#4]
Thanks for all your work on this! Our organization has several .NET 4.x websites that will take some time to migrate to .NET Core/.NET 5. Could you add some samples for integrating Identity Server with .NET 4.x websites?

**Comment by brockallen** [comment]
A web forms sample was added last week:

https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5/Clients/WebForms

That's not the best location for it, so we might move it in the future somewhere else in this repo.
