### ISSUE TITLE
Google Auth : The oauth state was missing or invalid.

### ISSUE THREAD

**Issue by ramantsitou** [DuendeSoftware/Samples#48]
I use [3_AspNetCoreAndApis](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5/Quickstarts/3_AspNetCoreAndApis). I've added my ClientId and ClientSecret, run the project and open [/signin-google](https://localhost:5001/signin-google)
The browser shows me the following error page:
![image](https://user-images.githubusercontent.com/11888679/161088829-4b3d75d1-2c9e-47a6-90a8-3f4bb3dc8cb2.png)

The same error I see for V5 and V6.

Is it something I'm doing wrong, or Google authentication just doesn't work?

**Comment by brockallen** [comment]
It's working for me locally, so not sure, sorry. This could be very environmental (wrong redirect uri, wrong host configured). I'd suggest getting google to work in a stand alone ASP.NET Core sample, then compare that to what you have different in the quickstart.
