### ISSUE TITLE
Requesting to add a custom property to example 5 in ApplicationUser

### ISSUE THREAD

**Issue by michelbieleveld** [DuendeSoftware/Samples#53]
Hi I am struggling to get a custom property added to the id token using asp identity in combination with IdentityServer. It would be great if example 5 added a custom property like given name to it and show the additional code to get that available in the id token. Documentation does mention it is possible,  but thusfar haven't found out how, likely something with IUserClaimsPrincipalFactory and the profile service.

**Comment by brockallen** [comment]
@josephdecock feel free to add something like this where appropriate in the QS docs/samples. ty!

**Comment by josephdecock** [comment]
The quickstart docs and sample are updated. Closing.
