### ISSUE TITLE
1_ClientCredentials : Unable to authenticate API

### ISSUE THREAD

**Issue by dineshgade** [DuendeSoftware/Samples#56]
We are implementing security for an API that is being accessed by the client. The API is added as a scope for the Client. We are passing the token to the API. User is not being authenticated in API when using the [Authorize] attribute.  api1 is added as a scope for the Client.

**Comment by brockallen** [comment]
Can you explain more or provide more details of what's not working?

**Comment by dineshgade** [comment]
The [Authorize] attribute is denying the access to the API resource. Is there a way to find out whether the request has gone to the Identity Server from the API, and it responded with Deny.

**Comment by brockallen** [comment]
And you're saying that our quickstart sample does not work?

**Comment by gadedineshreddy** [comment]
The sample application works. When the Api is a SignalR hub it is not working. Working fine with Web Api.

**Comment by brockallen** [comment]
> When the Api is a SignalR hub it is not working

SignalR endpoint are not Web API endpoints -- they work differently, and this quickstart does not show how to authenticate to web socket endpoints. We don't have a SignalR sample, since web sockets don't allow passing the authorize request header, so the recommendation is to have your app use a cookie.

**Comment by dineshgade** [comment]
The Token is being passed as a Query String parameter and setting the context on OnMessageReceived JwtBearer Event. I hope cookie is used to do the same thing. 

          `services.AddAuthentication(options =>
            {
                // Identity made Cookie authentication the default.
                // However, we want JWT Bearer Auth to be the default.
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
              //.AddIdentityServerJwt()
              .AddJwtBearer("Bearer", options =>
             {
                 options.Authority = Configuration["AppSettings:IdentityServiceUrl"];
                 options.IncludeErrorDetails = true;
                 options.Audience = "Hub";

                 options.TokenValidationParameters = new TokenValidationParameters
                 {
                     ValidateAudience = false,
                     //ValidateIssuerSigningKey = false,
                     //ValidateIssuer = false
                 };

                 options.Events = new JwtBearerEvents
                 {
                     OnMessageReceived = context =>
                     {
                         // Is token in Querystring?
                          var accessToken = context.Request.Query["access_token"];
                         
                         if (!string.IsNullOrWhiteSpace(accessToken))
                         {
                             var path = context.HttpContext.Request.Path;
                             if (path.StartsWithSegments("/tradehub"))
                             {
                                 // Read the token out of the query string
                                 context.Token = accessToken;
                             }
                         }
                         return Task.CompletedTask;
                     },
                     OnChallenge = context =>
                     {
                         context.HandleResponse();
                         context.Response.StatusCode = StatusCodes.Status401Unauthorized;
                         context.Response.ContentType = "application/json";

                         // Ensure we always have an error and error description.
                         if (string.IsNullOrEmpty(context.Error))
                             context.Error = "invalid_token";
                         if (string.IsNullOrEmpty(context.ErrorDescription))
                             context.ErrorDescription = "This request requires a valid JWT access token to be provided";

                         // Add some extra context for expired tokens.
                         if (context.AuthenticateFailure != null && context.AuthenticateFailure.GetType() == typeof(SecurityTokenExpiredException))
                         {
                             var authenticationException = context.AuthenticateFailure as SecurityTokenExpiredException;
                             context.Response.Headers.Add("x-token-expired", authenticationException.Expires.ToString("o"));
                             context.ErrorDescription = $"The token expired on {authenticationException.Expires.ToString("o")}";
                         }

                         return context.Response.WriteAsync(JsonSerializer.Serialize(new
                         {
                             error = context.Error,
                             error_description = context.ErrorDescription
                         }));
                     }

                 };
             });`

**Comment by brockallen** [comment]
Given that access tokens and OIDC/OAuth2 are really orthogonal to SignalR, I'm not sure we need a sample. What do the Microsoft docs show for how to authenticate? I'd imagine they use the cookie authentication handler. If you can find a link to what they propose, that would be helpful.

**Comment by dineshgade** [comment]
Following the Microsoft documentation guidelines:
https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0

**Comment by brockallen** [comment]
I'm surprised they show using access tokens in those docs, as access tokens sent in query params are bad practice and forbidden by OAuth: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-5.2.1

**Comment by brockallen** [comment]
Hi @dineshgade  -- where do we stand on this issue. Is there still a request for us here?

**Comment by dineshgade** [comment]
Yes. Still trying to figure out what's missing. If you could provide a sample, that would be great.

**Comment by brockallen** [comment]
Sample for what? SignalR accepting access tokens? I'm not sure that's what I'd recommend, to be honest.

**Comment by brockallen** [comment]
Given that SignalR is based on web sockets and that you can't pass an authorization header, and that access tokens are forbidden from using in URLs, and that Microsoft already has some docs on this, I don't think we should be putting out a sample at this time.
