### ISSUE TITLE
ReactBffSample is not using BackendAPIHost /todos

### ISSUE THREAD

**Issue by ramganesh19** [DuendeSoftware/Samples#58]
Tried un commenting the below line in program.cs (frontendhost) to make use of remote api(BackendAPIHost ) and unclear if i have to make more change to have YARP configuration to make it work

 app.MapRemoteBffApiEndpoint("/todos", "https://localhost:5020/todos")
     .RequireAccessToken(Duende.Bff.TokenType.User);

Appreciate any help?

**Comment by leastprivilege** [comment]
That's it. Isn't it working?

**Comment by ramganesh19** [comment]
No its not. When I debug the code only the FrontendHost project \ReactBffSample\src\FrontendHost\Controllers\ToDoController.cs is getting invoked and not the \ReactBffSample\src\BackendApiHost\ToDoController.cs

**Comment by ramganesh19** [comment]
Reviewing the document and the sample code, my understanding is the solution leverages the built in forwarder to route "/todos", "https://localhost:5020/todos" to backendhost controller.

**Comment by leastprivilege** [comment]
This is because the local controller comes first in the routing table - remove the endpoint (or the controller). Then the backend will be hit.

**Comment by ramganesh19** [comment]
Thanks Got it working after
