### ISSUE TITLE
Question about MvcHybridBackChannel

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/Samples#6]
Hi.

I'm having trouble with the MvcHybridBackChannel sample.

The scenario is the following:

- Using Chrome, I sign-in to my client application (.NET Core MVC 3.1) and show a page with the user claims. Let's say SID is A and SUB is B.
- Using Egde, I sign-in to the same application/page. SID is X and SUB is B.

When I sign-out from Chrome, the session in Edge remains valid, because the SID claims were different and the code in LogoutSessionManager doesn't match the loggedout session received from the back-channel notification.

Pretty obvious as it will only match if SID and SUB are equal or one is null:

```
return (Sid == sid && Sub == sub) ||
  (Sid == sid && Sub == null) ||
  (Sid == null && Sub == sub);
```

What am I missing here?

Thanks.

**Comment by leastprivilege** [comment]
You are not missing anything ;)

The SIDs are different, because they are physically 2 different sessions. It is up to your notification code to implement the logic that you need.

You could e.g. ignore the session id, and just sign-out all sessions for a give sub.
