### ISSUE TITLE
Is it acceptable to use another app for `UserInteraction` props?

### ISSUE THREAD

**Issue by pdevito3** [DuendeSoftware/Samples#61]
So in [this example](https://github.com/DuendeSoftware/Samples/blob/3ac68fffe36d3914f9eaffef0afa0e3a47ded1f0/IdentityServer/v6/UserInteraction/SpaLoginUi/IdentityServerWithSpaLogin/Startup.cs#L31) for [using a SPA login page](https://docs.duendesoftware.com/identityserver/v6/samples/ui/#spa-style-login-page) you're referencing a local path to `wwwroot`, but I wanted to check if it's technically okay to use an external path to another SPA app before I go down a rabbit hole? 

I know this is normally not okay as it would a big gap for malicious actors, but doing it in the `UserInteraction` seems like it would essentially whitelist that known path, but maybe I'm missing something.

**Comment by brockallen** [comment]
You would have more complexity for the login UI SPA to be running elsewhere. But as long and this UI (wherever it runs) can securely establish the authentication session in the IdentityServer host, then you have your login. But you have lots of cross-site and/or CORS concerns there. IMO, it's much simpler and safer to run the UI co-hosted in your IdentityServer host.

**Comment by pdevito3** [comment]
Makes sense. 

I'm torn on as I personally find it significantly easier to develop UIs with something like react and can produce something much richer compared to a normal MVC app. Blazor checks some boxes, but still has gaps. And while it's possible to use react in the same project as teh auth server, there's hoops there too. 

Really just comes down to a trade off regardless, but good to know this is an option regardless. Thanks

**Comment by leastprivilege** [comment]
..and how rich does your login page need to be?
