### ISSUE TITLE
Improve Katana sample

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/Samples#62]
To get access tokens and use refresh tokens

https://github.com/DuendeSoftware/IdentityServer/discussions/936#discussioncomment-3013675

**Comment by leastprivilege** [comment]
Coincidentally we spoke about this yesterday on Signal

* upgrade to use latest Katana with code flow and PKCE
* request access and refresh token
* show how use access token
* show how to use refresh token

Maybe do this in an MVC sample and not webforms?

@josephdecock

**Comment by brockallen** [comment]
Also would be good to show a Katana based API host validating access tokens.

**Comment by josephdecock** [comment]
I have the basics ready to go for this in webforms. I'm thinking both webforms and mvc examples are useful. For the katana api validating tokens, do we want to use https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation?

**Comment by leastprivilege** [comment]
no. this is long deprecated. Please don't revive it ;)

**Comment by josephdecock** [comment]
That’s what I thought. What would you like to see in the sample instead?

**Comment by leastprivilege** [comment]
the plain Katana JWT middleware...

**Comment by leastprivilege** [comment]
I moved the WebForms sample to /various/clients - and also introduced a new section in our docs

https://docs.duendesoftware.com/identityserver/v6/samples/clients/

@josephdecock please use this folder for the updated WebForms and MVC sample. thanks!

**Comment by brockallen** [comment]
@josephdecock Can this issue be closed given the sample you just worked on?

**Comment by josephdecock** [comment]
Yes. I don’t seem to have permissions to associate issues to PRs in the
samples repo, or I would have made the link in the PR itself.

**Comment by brockallen** [comment]
No worries -- if there all the items in here are in the sample, then I'll just close this. Thx.
