### ISSUE TITLE
custom Validate username and password 

### ISSUE THREAD

**Issue by davidegolzi** [DuendeSoftware/Samples#64]
Where i can find example on how to configure the identity server on how manage the username and password validation?

like make a request on a service or queryng a custom database?

**Comment by davidegolzi** [comment]
i cannot find any examples

**Comment by brockallen** [comment]
> Where i can find example on how to configure the identity server on how manage the username and password validation?
> like make a request on a service or queryng a custom database?

This would just be custom code in your login page and up to you to decide how that works, but I feel like I'm misunderstanding your question.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
