### ISSUE TITLE
[Question] How to challenge directly to a particular external identity provider w/ Webforms & OIDC ex

### ISSUE THREAD

**Issue by GFoley83** [DuendeSoftware/Samples#65]
I'm extending a legacy Webforms multi-tenant app to integrate with a new, separate instance of Duende IdS, using your example from here as a starting point:   

https://github.com/DuendeSoftware/Samples/tree/daccd2748cdb1c6b5cb04cc519b51313ce0c59dd/various/clients/WebFormsOidcClient/WebForms

It's configured to use `UseOpenIdConnectAuthentication`, which points to my IdS instance. My IdS is configured with multiple identity providers e.g. Google, Microsoft and multiple other OIDC IdPs that are used for particular tenants only.

I'm using:
```csharp
HttpContext.Current.GetOwinContext().Authentication.Challenge(new AuthenticationProperties
{
    RedirectUri = ". . ."
}, "oidc"); // AuthenticationType = "oidc" in Startup.cs
```

So that I can challenge the user dynamically e.g. only under certain business rules. Currently, everything works correctly.

The part I'm stuck on is I'd like to be able to challenge directly to a particular external identity provider that's registered with my IdS instance, but I'm unsure how to do that here. 

By default the `HttpContext.Current.GetOwinContext().Authentication.Challenge(...)` will bring you to the login page of my IdentityServer instance (as in your example), but I'd like to be able to go directly to the external identity provide challenge page, just as if I'd clicked on one of the external login buttons on the login page.

Any help would be much appreciated.

**Comment by brockallen** [comment]
> The part I'm stuck on is I'd like to be able to challenge directly to a particular external identity provider that's registered with my IdS instance, but I'm unsure how to do that here.

Use `acr_values` parameter to the authorize endpoint with the "idp:Xxx" value:

https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/authorize/#optional-parameters

**Comment by GFoley83** [comment]
Thanks Brock. It took a small bit of searching to figure out how to apply the `acr_values` dynamically but I've settled on the follow approach for now which solves my problem:

```csharp
var properties = new AuthenticationProperties();
properties.Dictionary["Idp"] = identityProvider; // e.g. "Google" or any IdP I've already registered with my IdS instance
HttpContext.Current.GetOwinContext().Authentication.Challenge(properties, "oidc");
```

```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
    AuthenticationType = "oidc",
    SignInAsAuthenticationType = "cookies",

    Authority = Authority,

    ClientId = ". . .",
    ClientSecret = ". . .",

    RedirectUri = "https://localhost:44306/",
    PostLogoutRedirectUri = "https://localhost:44306/",

    ResponseType = "code id_token",
    Scope = "openid profile email tenant api",

    UseTokenLifetime = false,
    SaveTokens = true,
    RedeemCode = true,
    Notifications = new OpenIdConnectAuthenticationNotifications()
    {
        RedirectToIdentityProvider = ctx =>
        {
            if (ctx.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectRequestType.Authentication)
            {
                // Based on user input / business rules and not hard-coded startup values
                var idp = ctx.OwinContext.Authentication.AuthenticationResponseChallenge.Properties.Dictionary["Idp"];
                ctx.ProtocolMessage.AcrValues = $"idp:{idp}";
            }

            return Task.FromResult(0);
        }
    }
});
```

If there's a nicer way of doing this. please let me know. Otherwise, feel free to close.

**Comment by brockallen** [comment]
Yep, that's pretty much how I might have done it!
