### ISSUE TITLE
Error refreshing access token. Error = invalid_grant

### ISSUE THREAD

**Issue by ramganesh19** [DuendeSoftware/Samples#66]
My Access Token is set to expire

IdentityServer:
                ClientId = "web",
                ClientSecrets = { new Secret("**************************".Sha256()) },

                AllowedGrantTypes = GrantTypes.Code,
                AccessTokenLifetime = 120,

SPA Client:
// registers HTTP client that uses the managed user access token
builder.Services.AddUserAccessTokenHttpClient("user_client", configureClient: client =>
{
    client.BaseAddress = new Uri(apiBaseAddress);
});

I get below error in the log once the accesstoken expires.
**************SPAclient LOG*********************
warn: Duende.Bff[0]
      You do not have a valid license key for the Duende software. This is allowed for development and testing scenarios. If you are running in production you are required to have a licensed version. Please start a conversation with us: https://duendesoftware.com/contact
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7240
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5267
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\cfund\quickstart\src\FrontendHost\
info: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      No SPA development server running at https://localhost:44447 found.
info: Microsoft.AspNetCore.SpaProxy.SpaProxyMiddleware[0]
      SPA proxy is not ready. Returning temporary landing page.
info: Microsoft.AspNetCore.SpaProxy.SpaProxyMiddleware[0]
      SPA proxy is not ready. Returning temporary landing page.
info: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      SPA development server running at 'https://localhost:44447'
info: Microsoft.AspNetCore.SpaProxy.SpaProxyMiddleware[0]
      SPA proxy is ready. Redirecting to https://localhost:44447.
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.LogicalHandler[100]
      Start processing HTTP request POST https://localhost:5001/connect/token
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.ClientHandler[100]
      Sending HTTP request POST https://localhost:5001/connect/token
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.ClientHandler[101]
      Received HTTP response headers after 142.7934ms - 400
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.LogicalHandler[101]
      End processing HTTP request after 160.1737ms - 400
fail: IdentityModel.AspNetCore.AccessTokenManagement.UserAccessAccessTokenManagementService[0]
      Error refreshing access token. Error = invalid_grant
warn: Duende.Bff.RemoteApiEndpoints[4]
      Access token is missing. token type: 'User', local path: '/TradeOrder'.
warn: Duende.Bff.RemoteApiEndpoints[4]
      Access token is missing. token type: 'User', local path: '/TradeOrder'.
warn: Duende.Bff.RemoteApiEndpoints[4]
      Access token is missing. token type: 'User', local path: '/TradeOrder'.
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.LogicalHandler[100]
      Start processing HTTP request POST https://localhost:5001/connect/token
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.ClientHandler[100]
      Sending HTTP request POST https://localhost:5001/connect/token
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.ClientHandler[101]
      Received HTTP response headers after 85.0946ms - 400
info: System.Net.Http.HttpClient.IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.LogicalHandler[101]
      End processing HTTP request after 105.5918ms - 400
fail: IdentityModel.AspNetCore.AccessTokenManagement.UserAccessAccessTokenManagementService[0]
      Error refreshing access token. Error = invalid_grant
warn: Duende.Bff.RemoteApiEndpoints[4]
      Access token is missing. token type: 'User', local path: '/Order'.
warn: Duende.Bff.RemoteApiEndpoints[4]
      Access token is missing. token type: 'User', local path: '/Order'.
warn: Duende.Bff.RemoteApiEndpoints[4]
      Access token is missing. token type: 'User', local path: '/Order'.

**Comment by brockallen** [comment]
Sounds like the refresh token failed to renew. Check your IdentityServer logs for more info.

**Comment by brockallen** [comment]
Any updates on this?
