### ISSUE TITLE
Simple Angular/BFF sample

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/Samples#74]
Just basic login/logout/show user session for Angular using the MS Angular template as a starting point.

**Comment by barelabs** [comment]
I believe this pull request that was closed actually had this completed....I'm not the author of this, but it fully worked when I tested it... the author is @marleypowell

https://github.com/marleypowell/DuendeSamples/tree/marley/angular-sample/IdentityServer/v6/BFF/AngularBffSample

**Comment by marleypowell** [comment]
See: #63

**Comment by leastprivilege** [comment]
Yes - thanks for that!

But as we said earlier - the reality of today's software industry is that we cannot take responsibility of code originating outside of our organization. That's why we need our own sample.

**Comment by marleypowell** [comment]
That makes sense, thanks for adding one 🙂
