### ISSUE TITLE
BFF Blazor Server sample v5 not using the API project? 

### ISSUE THREAD

**Issue by VR-Architect** [DuendeSoftware/Samples#76]
I downloaded the BFF Blazor Server v5 sample.  I ran the Blazor project and was able to log Bob in.  Where is the Razor page that calls the included API project?  In particular,  I am testing to see if the API can get the logged in user's claims. I set both projects to start on debug.

**Comment by leastprivilege** [comment]
We realized that BFF does not really make sense with Blazor Server since you are already on the server.

In this case all you want in Blazor is really the token management bits which are not part of BFF anyways.

Have a look at this newer sample instead:
https://github.com/DuendeSoftware/Duende.AccessTokenManagement/tree/main/samples/BlazorServer

**Comment by VR-Architect** [comment]
Thanks. I built the AccessToken solution and received these errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.dll' could not be found	Worker	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\Worker\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.dll' could not be found	WorkerDI	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\WorkerDI\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.dll' could not be found	BlazorServer	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\BlazorServer\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement.OpenIdConnect\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.OpenIdConnect.dll' could not be found	BlazorServer	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\BlazorServer\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.dll' could not be found	Tests	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\test\Tests\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement.OpenIdConnect\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.OpenIdConnect.dll' could not be found	Tests	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\test\Tests\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.dll' could not be found	Web	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\Web\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement.OpenIdConnect\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.OpenIdConnect.dll' could not be found	Web	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\Web\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.dll' could not be found	WebJarJwt	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\WebJarJwt\CSC	1	Active
Error	CS0006	Metadata file 'D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement.OpenIdConnect\obj\Debug\net6.0\ref\Duende.AccessTokenManagement.OpenIdConnect.dll' could not be found	WebJarJwt	D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\samples\WebJarJwt\CSC	1	Active
Error	MSB3073	The command "dotnet "C:\Users\Brian\.nuget\packages\minver\4.0.0\build\../minver/MinVer.dll" "D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement" --auto-increment "" --build-metadata "" --default-pre-release-phase "" --minimum-major-minor "" --tag-prefix "" --verbosity "" --version-override """ exited with code -532462766.	Duende.AccessTokenManagement	C:\Users\Brian\.nuget\packages\minver\4.0.0\build\MinVer.targets	44	
Error	MSB3073	The command "dotnet "C:\Users\Brian\.nuget\packages\minver\4.0.0\build\../minver/MinVer.dll" "D:\Voogu\VS Projects\Duende.AccessTokenManagement-main\src\Duende.AccessTokenManagement.OpenIdConnect" --auto-increment "" --build-metadata "" --default-pre-release-phase "" --minimum-major-minor "" --tag-prefix "" --verbosity "" --version-override """ exited with code -532462766.	Duende.AccessTokenManagement.OpenIdConnect	C:\Users\Brian\.nuget\packages\minver\4.0.0\build\MinVer.targets	44

**Comment by leastprivilege** [comment]
Do you have git installed?

Feel free to just use the Blazor Sample with the Nuget package instead.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
