### ISSUE TITLE
Can bff/user return the user avatar address?

### ISSUE THREAD

**Issue by qq1176914912** [DuendeSoftware/Samples#85]
/bff/user gets the values as shown in the figure by default. Can I get the user address through /bff/use?
![image](https://user-images.githubusercontent.com/79817742/194833600-c393c245-b4e9-4309-9911-8193db24e66b.png)

**Comment by qq1176914912** [comment]
Something similar to getting /connect/userinfo

**Comment by leastprivilege** [comment]
duplicate

**Comment by josephdecock** [comment]
An alternative is to have the OIDC middleware call the userinfo endpoint by setting the `GetClaimsFromUserInfoEndpoint` to true, and then map the address claim from userinfo into the session with `ClaimActions.MapUniqueJsonKey("address", "address")`.

**Comment by qq1176914912** [comment]
> 
Thank you, this method is feasible
