### ISSUE TITLE
Server-side sessions vs. older MvcHybridBackChannel sample

### ISSUE THREAD

**Issue by nikriaz** [DuendeSoftware/Samples#90]
As soon as I understand this, a part of older approach in [MvcHybridBackChannel sample](https://github.com/DuendeSoftware/IdentityServer/tree/main/clients/src/MvcHybridBackChannel) (LogoutSessionManager.cs, CookieEventHandler.cs) assumes server-side sessions on a client side, while newer approach [suggests ](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/) that now server-side management is available on the IS side, so no need to repeat it on a client.

Would be really cool to get some info how to use this new feature. To be honest don't even know how to start as can't locate any basic concrete information, apart of architecture description. Newer client example with back-channel logout and IS-server-side sessions would be also highly appreciated.

**Comment by josephdecock** [comment]
Server side sessions in Identity server don't replace server side sessions at your application. The back channel logout mechanism in the sample you link to is still relevant-in fact an identity server server side session's expiration can trigger back channel logout.

The chapter in docs on server side sessions starts here:
https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/, and then continues on child pages discussing how to use it for session management and cross app inactivity timeouts. What questions do you still have after reading those docs?

**Comment by josephdecock** [comment]
Also, we have a sample of server side sessions: https://docs.duendesoftware.com/identityserver/v6/samples/misc/#session-management-sample

**Comment by nikriaz** [comment]
Many thanks for the answer! Yep, at first I missed these child pages and samples, thank you. But still IdS-server-side sessions vs. Client server-side versions is still unclear. Indeed, these sessions are different but the _list_ of these sessions (sids) are the same. What's the point to handle separate list of the subs and sids if we already have this list on IdS? This MVC sample already existed in pre-IdS-server-side sessions era but now I believe we don't need this extra handle anymore. 

![2022-12-13 22_46_16-Samples_LogoutSessionManager cs at main · DuendeSoftware_Samples](https://user-images.githubusercontent.com/52108512/207452246-800b3ca4-ab19-4d7a-98f3-64ba5f59dbe4.png)

**Comment by josephdecock** [comment]
You need a server side session at the application if you want to use a backchannel logout. If you don't do that, and your application session is entirely cookie based, then the only way you can interact with session state is if the cookie is sent, in other words, only on a front channel request. If on the other hand, you have server side session state at the application, then a backchannel request can be sent to the application without ever involving the browser and yet it can still interact with that session state.

**Comment by nikriaz** [comment]
Finally got it, thank you! Basically, we need an application server-side session to have an option to kill it even if the browser is closed. That is the essence of the backchannel logout. Okay, I probably meant the further evolvement of the architecture. Application can be IdS-server side session-based. Then, we don't even need a backchannel.

**Comment by nikriaz** [comment]
I have implemented and tested this approach without app-level list of sessions with such a kind of [cookie validator.](https://stackoverflow.com/questions/60858985/addopenidconnect-and-refresh-tokens-in-asp-net-core). We even don't have to care about sid because IdS invalidates refresh token when the session is deleted - as you confirmed in another thread. It works nice as expected and I don't see any operational and architectural drawbacks. Do you?
