### ISSUE TITLE
Grace period for reusing consumed refresh tokens

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/Samples#94]
Show how to extend `AcceptConsumedTokenAsync` to allow consumed tokens to be reused for a short grace period.

We do already document this feature [here](https://docs.duendesoftware.com/identityserver/v6/tokens/refresh/#one-time-refresh-tokens) - consider adding code sample inline in the docs.

**Comment by josephdecock** [comment]
Came up in a support issue: https://github.com/DuendeSoftware/Support/issues/406

**Comment by brockallen** [comment]
Given the updated guidance, we discourage this approach and thus don't need a sample.
